/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: LPC845
package_id: LPC845M301JBD48
mcu_data: ksdk2_0
processor_version: 25.06.10
board: LPC845BREAKOUT
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a1bf1abb-ba15-4a89-8c58-09436b4ba743
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * CTIMER0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER0'
- type: 'ctimer'
- mode: 'Capture_Match'
- custom_name_enabled: 'false'
- type_id: 'ctimer_2.2.2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER0'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_IncreaseOnRiseEdge'
      - input_clk: 'kCTIMER_Capture_0'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'custom:30Mhz'
      - timerPrescaler: '1'
    - EnableTimerInInit: 'false'
    - matchChannels: []
    - captureChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER0_IRQn'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_NoCallback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER0_config = {
  .mode = kCTIMER_IncreaseOnRiseEdge,
  .input = kCTIMER_Capture_0,
  .prescale = 0
};

static void CTIMER0_init(void) {
  /* CTIMER0 peripheral initialization */
  CTIMER_Init(CTIMER0_PERIPHERAL, &CTIMER0_config);
}

/***********************************************************************************************************************
 * SPI0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SPI0'
- type: 'lpc_minispi'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpc_minispi_2.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'SPI0'
- config_sets:
  - fsl_spi:
    - spiConfig:
      - spi_mode: 'kSPI_Master'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - spi_master_config:
        - baudRate_Bps: '1000000'
        - clockPolarity: 'kSPI_ClockPolarityActiveHigh'
        - clockPhase: 'kSPI_ClockPhaseFirstEdge'
        - direction: 'kSPI_MsbFirst'
        - dataWidth_enum: 'kSPI_Data8Bits'
        - sselNumber: 'kSPI_Ssel0Assert'
        - sselPol: 'false'
        - enableLoopback: 'false'
        - enableMaster: 'true'
        - delayConfig:
          - preDelay: '0'
          - postDelay: '0'
          - frameDelay: '15'
          - transferDelay: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t SPI0_config = {
  .baudRate_Bps = 1000000UL,
  .clockPolarity = kSPI_ClockPolarityActiveHigh,
  .clockPhase = kSPI_ClockPhaseFirstEdge,
  .direction = kSPI_MsbFirst,
  .dataWidth = 7,
  .sselNumber = kSPI_Ssel0Assert,
  .sselPolarity = kSPI_SpolActiveAllLow,
  .enableLoopback = false,
  .enableMaster = true,
  .delayConfig = {
    .preDelay = 0U,
    .postDelay = 0U,
    .frameDelay = 15U,
    .transferDelay = 0U
  }
};

static void SPI0_init(void) {
  /* Initialization function */
  SPI_MasterInit(SPI0_PERIPHERAL, &SPI0_config, SPI0_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * USART0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'USART0'
- type: 'lpc_miniusart'
- mode: 'transfer'
- custom_name_enabled: 'false'
- type_id: 'lpc_miniusart_2.5.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'USART0'
- config_sets:
  - fsl_usart:
    - usartConfig:
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '9600'
      - syncMode: 'kUSART_SyncModeDisabled'
      - parityMode: 'kUSART_ParityDisabled'
      - stopBitCount: 'kUSART_OneStopBit'
      - bitCountPerChar: 'kUSART_8BitsPerChar'
      - loopback: 'false'
      - enableRx: 'true'
      - enableTx: 'true'
      - clockPolarity: 'kUSART_RxSampleOnFallingEdge'
      - enableContinuousSCLK: 'false'
      - enableHardwareFlowControl: 'false'
    - quick_selection: 'QS_USART_1'
  - Transfer_cfg:
    - transfer:
      - init_rx_transfer: 'true'
      - rx_transfer:
        - data_size: '16'
      - init_tx_transfer: 'true'
      - tx_transfer:
        - data_size: '64'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const usart_config_t USART0_config = {
  .baudRate_Bps = 9600UL,
  .syncMode = kUSART_SyncModeDisabled,
  .parityMode = kUSART_ParityDisabled,
  .stopBitCount = kUSART_OneStopBit,
  .bitCountPerChar = kUSART_8BitsPerChar,
  .loopback = false,
  .enableRx = true,
  .enableTx = true,
  .clockPolarity = kUSART_RxSampleOnFallingEdge,
  .enableContinuousSCLK = false,
  .enableHardwareFlowControl = false
};
usart_handle_t USART0_handle;
uint8_t USART0_rxBuffer[USART0_RX_BUFFER_SIZE];
usart_transfer_t USART0_rxTransfer = {
  .rxData = USART0_rxBuffer,
  .dataSize = USART0_RX_BUFFER_SIZE
};
uint8_t USART0_txBuffer[USART0_TX_BUFFER_SIZE];
usart_transfer_t USART0_txTransfer = {
  .data = USART0_txBuffer,
  .dataSize = USART0_TX_BUFFER_SIZE
};

static void USART0_init(void) {
  /* USART0 peripheral initialization */
  USART_Init(USART0_PERIPHERAL, &USART0_config, USART0_CLOCK_SOURCE);
  USART_TransferCreateHandle(USART0_PERIPHERAL, &USART0_handle, NULL, NULL);
}

/***********************************************************************************************************************
 * SCT0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SCT0'
- type: 'sctimer'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'sctimer_2.4.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'SCT0'
- config_sets:
  - main:
    - config:
      - clockMode: 'kSCTIMER_System_ClockMode'
      - clockSource: 'SynchronousFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - SCTInputClockSourceFreq: 'custom:0'
      - clockSelect: 'kSCTIMER_Clock_On_Rise_Input_0'
      - enableCounterUnify: 'true'
      - enableBidirection_l: 'false'
      - enableBidirection_h: 'false'
      - prescale_l: '1'
      - prescale_h: '1'
      - outInitState: ''
      - inputsync: ''
    - enableIRQ: 'false'
    - interrupt:
      - IRQn: 'SCT0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enableLTimer: 'true'
    - enableHTimer: 'false'
    - pwms:
      - 0:
        - output: 'kSCTIMER_Out_4'
        - level: 'kSCTIMER_HighTrue'
        - dutyCyclePercent: '5'
    - pwmMode: 'kSCTIMER_EdgeAlignedPwm'
    - pwmFrequency: '500'
    - events: []
    - states:
      - 0:
        - pwms: 'pwm0'
    - inputmux_init:
      - inputmux_func_group: 'noInit'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const sctimer_config_t SCT0_initConfig = {
  .enableCounterUnify = true,
  .clockMode = kSCTIMER_System_ClockMode,
  .clockSelect = kSCTIMER_Clock_On_Rise_Input_0,
  .enableBidirection_l = false,
  .enableBidirection_h = false,
  .prescale_l = 0U,
  .prescale_h = 0U,
  .outInitState = 0U,
  .inputsync = 0U
};
const sctimer_pwm_signal_param_t SCT0_pwmSignalsConfig[1] = {
  {
    .output = kSCTIMER_Out_4,
    .level = kSCTIMER_HighTrue,
    .dutyCyclePercent = 5U
  }
};
uint32_t SCT0_pwmEvent[1];

static void SCT0_init(void) {
  SCTIMER_Init(SCT0_PERIPHERAL, &SCT0_initConfig);
  /* Initialization of state 0 */
  SCTIMER_SetupPwm(SCT0_PERIPHERAL, &SCT0_pwmSignalsConfig[0], kSCTIMER_EdgeAlignedPwm, 500U, SCT0_CLOCK_FREQ, &SCT0_pwmEvent[0]);
  SCTIMER_StartTimer(SCT0_PERIPHERAL, kSCTIMER_Counter_U);
}

/***********************************************************************************************************************
 * DAC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DAC0'
- type: 'lpc_dac'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'lpc_dac_2.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DAC0'
- config_sets:
  - general:
    - general_config:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - settlingTime: 'kDAC_SettlingTimeIs1us'
    - enable_double_buffer: 'true'
    - buffer_value_input: '0'
    - counter_value_input: '1'
    - enable_dma: 'false'
    - enable_counter: 'true'
    - enableInterrupt: 'false'
    - interrupt:
      - IRQn: 'DAC0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const dac_config_t DAC0_config = {
  .settlingTime = kDAC_SettlingTimeIs1us
};

static void DAC0_init(void) {
  /* DAC0 initiation  */
  DAC_Init(DAC0_PERIPHERAL, &DAC0_config);
  /* DAC0 double buffering enabled */
  DAC_EnableDoubleBuffering(DAC0_PERIPHERAL, true);
  /* DAC0 set buffer value */
  DAC_SetBufferValue(DAC0_PERIPHERAL, DAC0_BUFFER_VALUE);
  /* DAC0 set counter value */
  DAC_SetCounterValue(DAC0_PERIPHERAL, DAC0_COUNTER_VALUE);
  /* DAC0 enable counter */
  DAC_EnableCounter(DAC0_PERIPHERAL, true);
}

/***********************************************************************************************************************
 * MRT0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'MRT0'
- type: 'mrt'
- mode: 'general_config'
- custom_name_enabled: 'false'
- type_id: 'mrt_2.0.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'MRT0'
- config_sets:
  - fsl_mrt:
    - mrtOperationMode: 'HSM'
    - clockSettingMRT:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'custom:7.5MHz'
    - mrtChannels:
      - 0:
        - mrtChannelPrefixID: 'Channel_0'
        - channelNumber: 'kMRT_Channel_0'
        - timerMode: 'kMRT_RepeatMode'
        - timerValueStr: '1s'
        - startTimer: 'false'
        - enableInterruptRequest: 'true'
    - interruptVector:
      - enableInterrupt: 'true'
      - interrupt:
        - IRQn: 'MRT0_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const mrt_config_t MRT0_config = {
  .enableMultiTask = false
};

static void MRT0_init(void) {
  /* MRT0 peripheral initialization */
  MRT_Init(MRT0_PERIPHERAL, &MRT0_config);
  /* MRT channel 0 of MRT0 peripheral initialization */
  MRT_SetupChannelMode(MRT0_PERIPHERAL, MRT0_CHANNEL_0, MRT0_CHANNEL_0_MODE);
  /* MRT channel 0 interrupt of MRT0 peripheral initialization */
  MRT_EnableInterrupts(MRT0_PERIPHERAL, MRT0_CHANNEL_0, kMRT_TimerInterruptEnable);
  /* Enable interrupt MRT0_IRQN request in the NVIC */
  EnableIRQ(MRT0_IRQN);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  CTIMER0_init();
  SPI0_init();
  USART0_init();
  SCT0_init();
  DAC0_init();
  MRT0_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
