/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_ctimer.h"
#include "fsl_clock.h"
#include "fsl_spi.h"
#include "fsl_usart.h"
#include "fsl_sctimer.h"
#include "fsl_dac.h"
#include "fsl_mrt.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define CTIMER0_PERIPHERAL CTIMER0
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER0_TICK_FREQ 30000000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER0_TICK_PERIOD 33UL
/* Definition of PWM period channel. */
#define CTIMER0_PWM_PERIOD_CH kCTIMER_Match_0
/* BOARD_InitPeripherals defines for SPI0 */
/* Definition of peripheral ID */
#define SPI0_PERIPHERAL ((SPI_Type *)SPI0)
/* Definition of the clock source frequency */
#define SPI0_CLOCK_SOURCE 30000000UL
/* BOARD_InitPeripherals defines for USART0 */
/* Definition of peripheral ID */
#define USART0_PERIPHERAL ((USART_Type *)USART0)
/* Definition of the clock source frequency */
#define USART0_CLOCK_SOURCE 30000000UL
/* Rx transfer buffer size. */
#define USART0_RX_BUFFER_SIZE 16
/* Tx transfer buffer size. */
#define USART0_TX_BUFFER_SIZE 64
/* BOARD_InitPeripherals defines for SCT0 */
/* Definition of peripheral ID */
#define SCT0_PERIPHERAL SCT0
/* Definition of clock source frequency */
#define SCT0_CLOCK_FREQ 30000000UL
/* SCT0 interrupt vector ID (number). */
#define SCT0_IRQN SCT0_IRQn
/* SCT0 interrupt handler identifier. */
#define SCT0_IRQHANDLER SCT0_IRQHandler
/* BOARD_InitPeripherals defines for DAC0 */
/* Definition of peripheral ID */
#define DAC0_PERIPHERAL ((DAC_Type *) DAC0_BASE)
/* Definition of DAC output value. */
#define DAC0_BUFFER_VALUE 0
/* Definition of DAC counter value. */
#define DAC0_COUNTER_VALUE 1
/* Definition of peripheral ID */
#define MRT0_PERIPHERAL MRT0
/* Definition of channel 0 ID */
#define MRT0_CHANNEL_0 kMRT_Channel_0
/* Definition of channel 0 mode */
#define MRT0_CHANNEL_0_MODE kMRT_RepeatMode
/* Definition of channel 0 timer in ticks */
#define MRT0_CHANNEL_0_TICKS 7500000U
/* MRT0 interrupt vector ID (number). */
#define MRT0_IRQN MRT0_IRQn
/* MRT0 interrupt handler identifier. */
#define MRT0_IRQHANDLER MRT0_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const ctimer_config_t CTIMER0_config;
extern const spi_master_config_t SPI0_config;
extern const usart_config_t USART0_config;
extern usart_handle_t USART0_handle;
extern uint8_t USART0_rxBuffer[USART0_RX_BUFFER_SIZE];
extern usart_transfer_t USART0_rxTransfer;
extern uint8_t USART0_txBuffer[USART0_TX_BUFFER_SIZE];
extern usart_transfer_t USART0_txTransfer;
extern const sctimer_config_t SCT0_initConfig;
extern const sctimer_pwm_signal_param_t SCT0_pwmSignalsConfig[1];
extern uint32_t SCT0_pwmEvent[1];
extern const dac_config_t DAC0_config;
extern const mrt_config_t MRT0_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
