/**
 * M24C32_EEPROM_I2C.c
 *
 *  Created on: 4 May 2025
 *      Author: talos
 *  M24C32 I2C EEPROM function definitions as they are described in the datasheet.
 */

#include "M24C32_EEPROM_I2C.h"
#include "fsl_i2c.h"

/**
 * Write a single byte
 * @param slave_addr
 * @param byte_msB_addr
 * @param byte_lsB_addr
 * @param data
 * @return
 */
uint8_t M24C32_byte_write(const uint8_t slave_addr, const uint8_t byte_msB_addr, const uint8_t byte_lsB_addr, const uint8_t *data) {
	uint8_t err = 0;
	uint8_t tx_buff[3];
	tx_buff[0] = byte_msB_addr;
	tx_buff[1] = byte_lsB_addr;
	tx_buff[2] = *data;
	uint32_t status;
    status = I2C_MasterStart(I2C0, slave_addr, kI2C_Write);
    if(status == kStatus_Success)
    	{
    		status = I2C_MasterWriteBlocking(I2C0, tx_buff, 3, kI2C_TransferDefaultFlag);
    		if(status != kStatus_Success){ err = 1; }
    	}
    	else{ err = 1; }
	//STOP generated by I2C_MasterWriteBlocking(..., defaultFlag)
	return err;
}

/**
 * Write 1-32 bytes to a page (b16-b5 are the same)
 * @param slave_addr
 * @param byte_msB_addr
 * @param byte_lsB_addr
 * @param data
 * @param data_len
 * @return
 */
uint8_t M24C32_page_write(const uint8_t slave_addr, const uint8_t byte_msB_addr, const uint8_t byte_lsB_addr, const uint8_t *data, const uint8_t data_len) {
	uint8_t err = 0;
	uint8_t tx_buff[2];
	tx_buff[0] = byte_msB_addr;
	tx_buff[1] = byte_lsB_addr;
	uint32_t status;
    status = I2C_MasterStart(I2C0, slave_addr, kI2C_Write);
    if(status == kStatus_Success)
    	{
    		status = I2C_MasterWriteBlocking(I2C0, tx_buff, 2, kI2C_TransferNoStopFlag);
    		if (status == kStatus_Success) {
    			status = I2C_MasterWriteBlocking(I2C0, data, data_len, kI2C_TransferDefaultFlag);
    		}
    		if(status != kStatus_Success){ err = 1; }
    	}
    	else{ err = 1; }
	//STOP generated by I2C_MasterWriteBlocking(..., defaultFlag)
	return err;
}

/**
 * Read a byte from the current (internal) position
 * @param slave_addr
 * @param data
 * @return
 */
uint8_t M24C32_curr_addr_read(const uint8_t slave_addr, uint8_t *data) {
	uint8_t err = 0;
	uint32_t status;
    status = I2C_MasterStart(I2C0, slave_addr, kI2C_Read);
    if(status == kStatus_Success)
    	{
    		status = I2C_MasterReadBlocking(I2C0, data, 1, kI2C_TransferDefaultFlag);
    		if(status != kStatus_Success){ err = 1; }
    	}
    	else{ err = 1; }
	//STOP generated by I2C_MasterWriteBlocking(..., defaultFlag)
	return err;
}

/**
 * Read a byte from a given address
 * @param slave_addr
 * @param byte_msB_addr
 * @param byte_lsB_addr
 * @param data
 * @return
 */
uint8_t M24C32_rand_addr_read(const uint8_t slave_addr, const uint8_t byte_msB_addr, const uint8_t byte_lsB_addr, uint8_t *data) {
	uint8_t err = 0;
	uint8_t tx_buff[2];
	tx_buff[0] = byte_msB_addr;
	tx_buff[1] = byte_lsB_addr;
	uint32_t status;
    status = I2C_MasterStart(I2C0, slave_addr, kI2C_Write);
    if(status == kStatus_Success)
    	{
    		status = I2C_MasterWriteBlocking(I2C0, tx_buff, 2, kI2C_TransferNoStopFlag);
    		if(status == kStatus_Success) {
    		    status = I2C_MasterStart(I2C0, slave_addr, kI2C_Read);
    		    if(status == kStatus_Success)
    		    	{
    		    		status = I2C_MasterReadBlocking(I2C0, data, 1, kI2C_TransferDefaultFlag);
    		    		if(status != kStatus_Success){ err = 1; }
    		    	}
    		    else { err = 1;}
    		}
    		else { err = 1;}
    	}
    	else { err = 1; }
	//STOP generated by I2C_MasterWriteBlocking(..., defaultFlag)
	return err;
}

/**
 * Sequential read. Start from current (internal) position
 * @param slave_addr
 * @param data
 * @param data_len
 * @return
 */
uint8_t M24C32_seq_curr_addr_read(const uint8_t slave_addr, uint8_t *data, const uint8_t data_len) {
	uint8_t err = 0;
	uint32_t status;
    status = I2C_MasterStart(I2C0, slave_addr, kI2C_Read);
    if(status == kStatus_Success)
    	{
    		status = I2C_MasterReadBlocking(I2C0, data, data_len, kI2C_TransferDefaultFlag);
    		if(status != kStatus_Success){ err = 1; }
    	}
    	else{ err = 1; }
	//STOP generated by I2C_MasterWriteBlocking(..., defaultFlag)
	return err;
}

/**
 * Sequential read. Starts from a given address
 * @param slave_addr
 * @param byte_msB_addr
 * @param byte_lsB_addr
 * @param data
 * @param data_len
 * @return
 */
uint8_t M24C32_seq_rand_addr_read(const uint8_t slave_addr, const uint8_t byte_msB_addr, const uint8_t byte_lsB_addr, uint8_t *data, const uint8_t data_len) {
	uint8_t err = 0;
	uint8_t tx_buff[2];
	tx_buff[0] = byte_msB_addr;
	tx_buff[1] = byte_lsB_addr;
	uint32_t status;
    status = I2C_MasterStart(I2C0, slave_addr, kI2C_Write);
    if(status == kStatus_Success)
    	{
    		status = I2C_MasterWriteBlocking(I2C0, tx_buff, 2, kI2C_TransferNoStopFlag);
    		if(status == kStatus_Success) {
    		    status = I2C_MasterStart(I2C0, slave_addr, kI2C_Read);
    		    if(status == kStatus_Success)
    		    	{
    		    		status = I2C_MasterReadBlocking(I2C0, data, data_len, kI2C_TransferDefaultFlag);
    		    		if(status != kStatus_Success){ err = 1; }
    		    	}
    		    else { err = 1;}
    		}
    		else { err = 1;}
    	}
    	else { err = 1; }
	//STOP generated by I2C_MasterWriteBlocking(..., defaultFlag)
	return err;
}
